---
name: action

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  check_integrity:
    name: Expected local npm actions
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - run: npm run build-dist
      - name: Check if build left artifacts
        run: git diff --exit-code --ignore-space-at-eol

  check_action:
    name: Action
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0

  unit_tests_ubuntu:
    name: Unit tests (Ubuntu)
    strategy:
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-24.04-arm", "ubuntu-latest"]') }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test
        env:
          NODE_ENV: test
      - name: .tool-versions test
        id: setup-beam
        uses: ./
        with:
          install-rebar: false
          install-hex: false
          version-file: test/.tool-versions
          version-type: strict

  unit_tests_windows:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Unit tests (Windows)
    strategy:
      matrix:
        os:
          - windows-latest # x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - run: npm install --production
      - run: npm test
        env:
          NODE_ENV: test
      - name: .tool-versions test
        id: setup-beam
        uses: ./
        with:
          install-rebar: false
          install-hex: false
          version-file: test/.tool-versions
          version-type: strict

  unit_tests_macos:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Unit tests (macOS)
    strategy:
      matrix:
        os:
          - macos-latest # ARM64
          - macos-15-intel # x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test
        env:
          NODE_ENV: test
